# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: James Albright
  email: G00379271@atu.ie
description: ""

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
